/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cec.chronicles.popup.puzzle;

import javax.swing.*;

import cec.chronicles.popup.AbstractCECPopup;
import cec.chronicles.states.GameState;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 * Blank filling puzzle
 * 
 * @author Pýnar Ayaz
 * @version 10.5.2017
 */
public class BlankPanel extends AbstractCECPopup {

	private static final long serialVersionUID = -8674202221239534727L;

	/**
	 * Constructor
	 * 
	 * @param frame
	 */
	public BlankPanel(JFrame frame) {
		super(frame);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		label1 = new java.awt.Label();
		label2 = new java.awt.Label();
		label3 = new java.awt.Label();
		label4 = new java.awt.Label();
		label5 = new java.awt.Label();
		label6 = new java.awt.Label();
		label7 = new java.awt.Label();
		label8 = new java.awt.Label();
		label9 = new java.awt.Label();
		label10 = new java.awt.Label();
		textField1 = new java.awt.TextField();
		textField2 = new java.awt.TextField();
		label14 = new java.awt.Label();
		label15 = new java.awt.Label();
		label16 = new java.awt.Label();
		textField3 = new java.awt.TextField();
		textField4 = new java.awt.TextField();
		textField5 = new java.awt.TextField();
		label17 = new java.awt.Label();
		label18 = new java.awt.Label();
		label19 = new java.awt.Label();
		label20 = new java.awt.Label();
		label21 = new java.awt.Label();
		label22 = new java.awt.Label();
		textField6 = new java.awt.TextField();
		textField7 = new java.awt.TextField();
		textField8 = new java.awt.TextField();
		label23 = new java.awt.Label();
		textField9 = new java.awt.TextField();
		textField10 = new java.awt.TextField();
		textField11 = new java.awt.TextField();
		textField12 = new java.awt.TextField();
		label24 = new java.awt.Label();
		label25 = new java.awt.Label();
		label26 = new java.awt.Label();
		label27 = new java.awt.Label();
		label28 = new java.awt.Label();
		label30 = new java.awt.Label();
		label31 = new java.awt.Label();
		label32 = new java.awt.Label();
		jButton1 = new javax.swing.JButton();

		label1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
		label1.setText("It seems that some of the buttons on the ATM machine are not working!");

		label2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
		label2.setText("Unfortunately these numbers are exactly what Professor has to use to type in his password.");

		label3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
		label3.setText(
				"If you want to eat tonight, you have to help him out and construct the numbers of the password with the working buttons and math operators.");

		label4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
		label4.setText("Denver's Password: 2792");

		label5.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
		label5.setText("import java.util.Scanner;\n");

		label6.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
		label6.setText("public class ATM{");

		label7.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
		label7.setText("public static void main(String[] args){");

		label8.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
		label8.setText("System.out.print(");

		label9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
		label9.setText("  -");

		label10.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
		label10.setText(");");

		textField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				textField1ActionPerformed(evt);
			}
		});

		label14.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
		label14.setText("System.out.print( (");

		label15.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
		label15.setText("System.out.print(");

		label16.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
		label16.setText("System.out.print( ( (");

		label17.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
		label17.setText(")");

		label18.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
		label18.setText(" +");

		label19.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
		label19.setText(");");

		label20.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
		label20.setText(" /");

		label21.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
		label21.setText(" %");

		label22.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
		label22.setText(" +");

		label23.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
		label23.setText(");");

		label24.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
		label24.setText(" +");

		label25.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
		label25.setText(" /");

		label26.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
		label26.setText(" *");

		label27.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		label27.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
		label27.setText(")");

		label28.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
		label28.setText(")");

		label30.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
		label30.setText("}");

		label31.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
		label31.setText("}");

		label32.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
		label32.setText(");");

		jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
		jButton1.setText("Check");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(28).addGroup(layout
						.createParallelGroup(Alignment.LEADING).addComponent(getDoneButton()).addComponent(jButton1)
						.addComponent(label7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addComponent(label6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addComponent(label5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addComponent(label4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addComponent(label3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addGroup(layout.createSequentialGroup()
								.addComponent(label1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addGap(1)
								.addComponent(label2, GroupLayout.PREFERRED_SIZE, 774, GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createSequentialGroup()
								.addGap(92).addGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout
										.createSequentialGroup()
										.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
												.addGroup(layout.createSequentialGroup()
														.addComponent(label15, GroupLayout.PREFERRED_SIZE, 145,
																GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(ComponentPlacement.RELATED)
														.addComponent(textField8, GroupLayout.PREFERRED_SIZE, 20,
																GroupLayout.PREFERRED_SIZE)
														.addGap(2)
														.addComponent(label21, GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(ComponentPlacement.RELATED,
																GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(textField7, GroupLayout.PREFERRED_SIZE, 20,
																GroupLayout.PREFERRED_SIZE))
												.addGroup(layout.createSequentialGroup()
														.addComponent(label8, GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(ComponentPlacement.RELATED)
														.addComponent(textField1, GroupLayout.PREFERRED_SIZE, 20,
																GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(ComponentPlacement.RELATED)
														.addComponent(label9, GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(ComponentPlacement.RELATED).addComponent(
																textField2, GroupLayout.PREFERRED_SIZE, 20,
																GroupLayout.PREFERRED_SIZE))
												.addComponent(label31, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
												.addGroup(layout.createSequentialGroup().addGroup(layout
														.createParallelGroup(Alignment.LEADING)
														.addGroup(layout.createSequentialGroup()
																.addComponent(label14, GroupLayout.DEFAULT_SIZE,
																		GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																.addGap(37))
														.addGroup(layout.createSequentialGroup().addGap(174)
																.addComponent(textField5, GroupLayout.PREFERRED_SIZE,
																		20, GroupLayout.PREFERRED_SIZE)))
														.addComponent(label18, GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
														.addGap(7)))
										.addPreferredGap(ComponentPlacement.RELATED)
										.addGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout
												.createSequentialGroup()
												.addGroup(layout
														.createParallelGroup(Alignment.TRAILING, false).addGroup(layout
																.createSequentialGroup()
																.addComponent(textField4, GroupLayout.PREFERRED_SIZE,
																		20, GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(ComponentPlacement.RELATED,
																		GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																.addComponent(label17, GroupLayout.PREFERRED_SIZE,
																		GroupLayout.DEFAULT_SIZE,
																		GroupLayout.PREFERRED_SIZE))
														.addGroup(layout.createSequentialGroup()
																.addComponent(label22, GroupLayout.PREFERRED_SIZE,
																		GroupLayout.DEFAULT_SIZE,
																		GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(ComponentPlacement.RELATED)
																.addComponent(textField9, GroupLayout.PREFERRED_SIZE,
																		20, GroupLayout.PREFERRED_SIZE)))
												.addGap(20)
												.addGroup(layout.createParallelGroup(Alignment.TRAILING)
														.addComponent(label23, GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
														.addGroup(layout.createSequentialGroup()
																.addComponent(label20, GroupLayout.PREFERRED_SIZE,
																		GroupLayout.DEFAULT_SIZE,
																		GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(ComponentPlacement.RELATED)
																.addComponent(textField3, GroupLayout.PREFERRED_SIZE,
																		20, GroupLayout.PREFERRED_SIZE)))
												.addGap(20).addComponent(label19, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
												.addGroup(layout.createSequentialGroup().addGap(23).addComponent(
														label10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
														GroupLayout.PREFERRED_SIZE))))
										.addGroup(layout.createSequentialGroup()
												.addComponent(label16, GroupLayout.PREFERRED_SIZE, 177,
														GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(ComponentPlacement.RELATED)
												.addComponent(textField12, GroupLayout.PREFERRED_SIZE, 20,
														GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(ComponentPlacement.RELATED)
												.addComponent(label24, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(ComponentPlacement.RELATED)
												.addComponent(textField6, GroupLayout.PREFERRED_SIZE, 20,
														GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(ComponentPlacement.RELATED)
												.addComponent(label27, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(ComponentPlacement.RELATED)
												.addComponent(label25, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(ComponentPlacement.RELATED)
												.addComponent(textField11, GroupLayout.PREFERRED_SIZE, 20,
														GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(ComponentPlacement.RELATED)
												.addComponent(label28, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
												.addGap(1)
												.addComponent(label26, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(ComponentPlacement.RELATED)
												.addComponent(textField10, GroupLayout.PREFERRED_SIZE, 20,
														GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(ComponentPlacement.RELATED).addComponent(label32,
														GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
														GroupLayout.PREFERRED_SIZE))))
						.addComponent(label30, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE))
						.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(
				layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(label1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(label2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE))
						.addGap(1)
						.addComponent(label3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(label4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(label5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(label6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(label7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addGroup(layout
								.createParallelGroup(
										Alignment.TRAILING)
								.addGroup(
										layout.createSequentialGroup().addGroup(layout.createParallelGroup(
												Alignment.TRAILING)
												.addGroup(layout
														.createSequentialGroup().addGroup(layout
																.createParallelGroup(Alignment.TRAILING).addGroup(layout
																		.createParallelGroup(Alignment.LEADING)
																		.addComponent(label9,
																				GroupLayout.PREFERRED_SIZE,
																				GroupLayout.DEFAULT_SIZE,
																				GroupLayout.PREFERRED_SIZE)
																		.addGroup(layout
																				.createParallelGroup(Alignment.TRAILING)
																				.addComponent(label8,
																						GroupLayout.PREFERRED_SIZE,
																						GroupLayout.DEFAULT_SIZE,
																						GroupLayout.PREFERRED_SIZE)
																				.addComponent(textField1,
																						GroupLayout.PREFERRED_SIZE,
																						GroupLayout.DEFAULT_SIZE,
																						GroupLayout.PREFERRED_SIZE))
																		.addComponent(
																				textField2, GroupLayout.PREFERRED_SIZE,
																				GroupLayout.DEFAULT_SIZE,
																				GroupLayout.PREFERRED_SIZE))
																.addGroup(layout.createSequentialGroup()
																		.addComponent(label10,
																				GroupLayout.PREFERRED_SIZE,
																				GroupLayout.DEFAULT_SIZE,
																				GroupLayout.PREFERRED_SIZE)
																		.addGap(3)))
														.addGap(19)
														.addGroup(layout.createParallelGroup(Alignment.TRAILING)
																.addGroup(layout.createParallelGroup(Alignment.LEADING)
																		.addComponent(textField5,
																				GroupLayout.PREFERRED_SIZE,
																				GroupLayout.DEFAULT_SIZE,
																				GroupLayout.PREFERRED_SIZE)
																		.addComponent(label14,
																				GroupLayout.PREFERRED_SIZE,
																				GroupLayout.DEFAULT_SIZE,
																				GroupLayout.PREFERRED_SIZE))
																.addGroup(layout.createSequentialGroup().addGroup(layout
																		.createParallelGroup(Alignment.LEADING)
																		.addComponent(label18,
																				GroupLayout.PREFERRED_SIZE,
																				GroupLayout.DEFAULT_SIZE,
																				GroupLayout.PREFERRED_SIZE)
																		.addGroup(layout
																				.createParallelGroup(Alignment.TRAILING)
																				.addComponent(label17,
																						GroupLayout.PREFERRED_SIZE,
																						GroupLayout.DEFAULT_SIZE,
																						GroupLayout.PREFERRED_SIZE)
																				.addComponent(textField4,
																						GroupLayout.PREFERRED_SIZE,
																						GroupLayout.DEFAULT_SIZE,
																						GroupLayout.PREFERRED_SIZE)))
																		.addGap(1))))
												.addComponent(label20, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
												.addGroup(layout.createParallelGroup(Alignment.LEADING)
														.addComponent(label19, GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
														.addComponent(textField3, GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
												.addGroup(layout.createParallelGroup(Alignment.LEADING)
														.addGroup(layout.createSequentialGroup().addGap(78)
																.addComponent(label27, GroupLayout.PREFERRED_SIZE,
																		GroupLayout.DEFAULT_SIZE,
																		GroupLayout.PREFERRED_SIZE))
														.addGroup(layout.createSequentialGroup().addGap(76)
																.addComponent(textField11, GroupLayout.PREFERRED_SIZE,
																		GroupLayout.DEFAULT_SIZE,
																		GroupLayout.PREFERRED_SIZE))
														.addGroup(layout.createSequentialGroup().addGap(75)
																.addGroup(layout.createParallelGroup(Alignment.TRAILING)
																		.addComponent(label32,
																				GroupLayout.PREFERRED_SIZE,
																				GroupLayout.DEFAULT_SIZE,
																				GroupLayout.PREFERRED_SIZE)
																		.addComponent(textField10,
																				GroupLayout.PREFERRED_SIZE,
																				GroupLayout.DEFAULT_SIZE,
																				GroupLayout.PREFERRED_SIZE)))
														.addGroup(layout.createSequentialGroup()
																.addPreferredGap(ComponentPlacement.RELATED, 20,
																		Short.MAX_VALUE)
																.addGroup(layout
																		.createParallelGroup(Alignment.TRAILING, false)
																		.addGroup(layout.createSequentialGroup()
																				.addGroup(layout
																						.createParallelGroup(
																								Alignment.TRAILING)
																						.addComponent(label15,
																								GroupLayout.PREFERRED_SIZE,
																								GroupLayout.DEFAULT_SIZE,
																								GroupLayout.PREFERRED_SIZE)
																						.addComponent(textField8,
																								GroupLayout.PREFERRED_SIZE,
																								GroupLayout.DEFAULT_SIZE,
																								GroupLayout.PREFERRED_SIZE)
																						.addComponent(label21,
																								GroupLayout.PREFERRED_SIZE,
																								GroupLayout.DEFAULT_SIZE,
																								GroupLayout.PREFERRED_SIZE)
																						.addComponent(textField7,
																								GroupLayout.PREFERRED_SIZE,
																								GroupLayout.DEFAULT_SIZE,
																								GroupLayout.PREFERRED_SIZE))
																				.addGap(27))
																		.addGroup(layout.createSequentialGroup()
																				.addGroup(layout
																						.createParallelGroup(
																								Alignment.TRAILING)
																						.addComponent(textField9,
																								GroupLayout.PREFERRED_SIZE,
																								GroupLayout.DEFAULT_SIZE,
																								GroupLayout.PREFERRED_SIZE)
																						.addGroup(layout
																								.createParallelGroup(
																										Alignment.LEADING)
																								.addComponent(label22,
																										GroupLayout.PREFERRED_SIZE,
																										GroupLayout.DEFAULT_SIZE,
																										GroupLayout.PREFERRED_SIZE)
																								.addGroup(
																										layout.createSequentialGroup()
																												.addGap(3)
																												.addComponent(
																														label23,
																														GroupLayout.PREFERRED_SIZE,
																														GroupLayout.DEFAULT_SIZE,
																														GroupLayout.PREFERRED_SIZE))))
																				.addGap(29)))
																.addGroup(layout.createParallelGroup(Alignment.TRAILING)
																		.addGroup(layout
																				.createParallelGroup(Alignment.LEADING)
																				.addComponent(label16,
																						GroupLayout.PREFERRED_SIZE,
																						GroupLayout.DEFAULT_SIZE,
																						GroupLayout.PREFERRED_SIZE)
																				.addComponent(textField12,
																						GroupLayout.PREFERRED_SIZE,
																						GroupLayout.DEFAULT_SIZE,
																						GroupLayout.PREFERRED_SIZE))
																		.addGroup(layout.createSequentialGroup()
																				.addGroup(layout
																						.createParallelGroup(
																								Alignment.TRAILING)
																						.addComponent(label24,
																								GroupLayout.PREFERRED_SIZE,
																								GroupLayout.DEFAULT_SIZE,
																								GroupLayout.PREFERRED_SIZE)
																						.addComponent(textField6,
																								GroupLayout.PREFERRED_SIZE,
																								GroupLayout.DEFAULT_SIZE,
																								GroupLayout.PREFERRED_SIZE))
																				.addGap(1))))))
								.addGroup(layout.createParallelGroup(Alignment.LEADING)
										.addComponent(label25, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(label28, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(label26, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)))
						.addGap(30)
						.addComponent(label31, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addGap(25)
						.addComponent(label30, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addGap(26).addComponent(jButton1).addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(getDoneButton()).addContainerGap(23, Short.MAX_VALUE)));
		this.setLayout(layout);

		label16.getAccessibleContext().setAccessibleName("System.out.print( ( (");
		label17.getAccessibleContext().setAccessibleName("");
		label18.getAccessibleContext().setAccessibleName(" +");
	}// </editor-fold>//GEN-END:initComponents

	public void checkCompletion() {
		if (GameState.player.getPuzzleCompletion(4)) {
			enableBackButton();
		}
	}

	private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textField1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_textField1ActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		int n1 = getInt(textField1.getText());
		int n2 = getInt(textField2.getText());

		int n3 = getInt(textField5.getText());
		int n4 = getInt(textField4.getText());
		int n5 = getInt(textField3.getText());

		int n6 = getInt(textField8.getText());
		int n7 = getInt(textField7.getText());
		int n8 = getInt(textField9.getText());

		int n9 = getInt(textField12.getText());
		int n10 = getInt(textField6.getText());
		int n11 = getInt(textField11.getText());
		int n12 = getInt(textField10.getText());

		if (n1 - n2 == 2 && n1 != 2 && n1 != 7 && n1 != 9 && n2 != 2 && n2 != 7 && n2 != 9 && n1 < 10 && n2 < 10) {
			if (((n3 + n4) / n5) == 7 && n3 != 2 && n3 != 7 && n3 != 9 && n4 != 2 && n4 != 7 && n4 != 9 && n5 != 2
					&& n5 != 7 && n5 != 9 && n3 < 10 && n4 < 10 && n5 < 10) {
				if (((n6 % n7) + n8) == 9 && n6 != 2 && n6 != 7 && n6 != 9 && n7 != 2 && n7 != 7 && n7 != 9 && n8 != 2
						&& n8 != 7 && n8 != 9 && n6 < 10 && n7 < 10 && n8 < 10) {
					if ((((4 + 6) / 5) * 1) == 2 && n9 != 2 && n9 != 7 && n9 != 9 && n10 != 2 && n10 != 7 && n10 != 9
							&& n11 != 2 && n11 != 7 && n11 != 9 && n12 != 2 && n12 != 7 && n12 != 9 && n9 < 10
							&& n10 < 10 && n11 < 10 && n12 < 10) {
						enableBackButton();
						GameState.player.completePuzzle(4);
					}
				}
			}
		}

	}// GEN-LAST:event_jButton1ActionPerformed

	public int getInt(String s) {
		int num = -1;
		try {
			num = Integer.parseInt(s);
		} catch (Exception e) {
			return num;
		}
		return num;
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private java.awt.Label label1;
	private java.awt.Label label10;
	private java.awt.Label label14;
	private java.awt.Label label15;
	private java.awt.Label label16;
	private java.awt.Label label17;
	private java.awt.Label label18;
	private java.awt.Label label19;
	private java.awt.Label label2;
	private java.awt.Label label20;
	private java.awt.Label label21;
	private java.awt.Label label22;
	private java.awt.Label label23;
	private java.awt.Label label24;
	private java.awt.Label label25;
	private java.awt.Label label26;
	private java.awt.Label label27;
	private java.awt.Label label28;
	private java.awt.Label label3;
	private java.awt.Label label30;
	private java.awt.Label label31;
	private java.awt.Label label32;
	private java.awt.Label label4;
	private java.awt.Label label5;
	private java.awt.Label label6;
	private java.awt.Label label7;
	private java.awt.Label label8;
	private java.awt.Label label9;
	private java.awt.TextField textField1;
	private java.awt.TextField textField10;
	private java.awt.TextField textField11;
	private java.awt.TextField textField12;
	private java.awt.TextField textField2;
	private java.awt.TextField textField3;
	private java.awt.TextField textField4;
	private java.awt.TextField textField5;
	private java.awt.TextField textField6;
	private java.awt.TextField textField7;
	private java.awt.TextField textField8;
	private java.awt.TextField textField9;
}